#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt update
sudo apt -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/*.html
echo "Hello World!" > /var/www/html/*.html
sudo service nginx start
sudo ngink -s reload
sudo curl localhost
